rmdir "./00-Release/cs" /S /Q
rmdir "./00-Release/de" /S /Q
rmdir "./00-Release/es" /S /Q
rmdir "./00-Release/fr" /S /Q
rmdir "./00-Release/it" /S /Q
rmdir "./00-Release/ja" /S /Q
rmdir "./00-Release/ko" /S /Q
rmdir "./00-Release/pl" /S /Q
rmdir "./00-Release/pt-BR" /S /Q
rmdir "./00-Release/ru" /S /Q
rmdir "./00-Release/tr" /S /Q
rmdir "./00-Release/zh-Hans" /S /Q
rmdir "./00-Release/zh-Hant" /S /Q
